# replicaCount: 1
# 
# image:
#   repository: host.docker.internal:5000/myapp 
#   tag: "dev" 
#   pullPolicy: IfNotPresent
# 
# imagePullSecrets: 
#   - name: nexus-secret
# service:

#   type: ClusterIP

#   port: 80 

# serviceAccount:

#   create: true 

#   automount: true 

#   name: "" 

#   annotations: {}

# ingress:

#   enabled: false 

# autoscaling:

#   enabled: false
replicaCount: 1
image:
  repository: 10.0.0.6:5000/myapp
  tag: "34"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: nexus-secret
service:
  type: ClusterIP
  port: 80
serviceAccount:
  create: true
  automount: true
  name: ""
  annotations: {}
ingress:
  enabled: false
autoscaling:
  enabled: false
